### ISSUE TITLE
Multiple Keys for an Entity seems to be broken, possibly by the new SLUG class

### ISSUE THREAD

**Issue by stevehof** [swl10/pyslet#40]
This is another thing I've noticed, I've got a potential fix my side and I'll make a pull request shortly. But basically from what i can see, you support multiple keys, but when you introduced the Slug class for HTTP_SLUG this broke how it stored it in the http headers.

**Comment by stevehof** [comment]
Pull request: https://github.com/swl10/pyslet/pull/41

**Comment by swl10** [comment]
OK, it turns out there were multiple issues.  Firstly, the single-valued case was not working at all because I was passing the Slug object instead of it's decoded string attribute when attempting to create keys.  The unittests were only checking use of the slug to map to syndicate title, not as a proper key hint.  I've added a test to catch that now.

Secondly, in the composite key case I've taken Atom at its word:

> Slug is an HTTP entity-header whose presence in a POST to a
   Collection constitutes a request by the client to use the header's
   value as part of any URIs that would normally be used to retrieve the
   to-be-created Entry or Media Resources.

So if you want to specify the key to use when posting a media stream you can now send the key-predicated formatted version of the key (in either single-value or composite key cases).  Use the brackets too, i.e., everything you would have put after the entity set name.  I've added code to the client to encode composite keys in new_stream in the same way.

This also helped catch a couple of other issues.

**Comment by stevehof** [comment]
Cool thanks! Look likes my testing code here was quite similar to yours in the end...
