### ISSUE TITLE
Garbage received when server delays response

### ISSUE THREAD

**Issue by karurosu** [swl10/pyslet#56]
Hello,
I am trying to use your library to talk to a TFS Odata server (https://tfsodata.visualstudio.com/)
Out of the box it won't work because the schema names conflict, after changing them, the server takes a while to respond to petitions and pyslet receives a bunch of \0x00 characters at the beginning of the response, which causes it to fail parsing the response.

I made a quick hack by changing line 215 of odata2.client to:
doc.read(request.res_body.strip("\x00"))

This does not happen with other libraries (like requests) so I am guessing its a bug in the http client implementation.

Edit: I accidentally used the latest master.
It doesn't seem to happen in 0.6.20160201, please delete if this request does not make sense.

**Comment by swl10** [comment]
Apologies for the delay looking into this.  I don't have access to a TFS OData server, would it be possible to post an anonymised session, perhaps with logging turned up to DEBUG to help me see what is happening?

The master would normally be the best to use as it has the latest fixes, since that date I did update the http client to work with Python 3 and it's possible that that has introduced an uncaught regression.  I'm keen to track this issue down but need a bit more info to help me.

**Comment by karurosu** [comment]
No problem.
I've been using Pyslet 0.6.20160201 without any problems.

I tried to debug the issue (in case it was something simple) but the http connection code was too complex for the limited time I had. My best guess is what I put in the first post.

I did try with the debug option and unfortunately there was not a lot of useful output. Right now I have to finish something with what is working, but afterwards I could try MASTER again and post a log.

Thanks, and awesome library, it has saved me a lot of work !

**Comment by swl10** [comment]
Thanks for the response.  For info I realised that you can get a free account on visualstudio.com so I was able to create a simple project with one related work item and run a small test today using the code in master.  I wasn't able to reproduce the problem I'm afraid, I used 2.7.10, 2.6.6 and 3.5.1 all running on a OS X.  If you have time, could you post the Python version and OS you used?

**Comment by karurosu** [comment]
This is a windows 8.1 system running python 2.7.10 64 bits.

It is probably a weird corner case of my system and the version of TFS used. I'll try to reproduce when I get a chance.

**Comment by swl10** [comment]
I've tested on my own Windows environment and can't reproduce but it's Windows 7, python 2.7.11 32b so still plenty of room for differences.

The key change I made after 0.6.20160201 was to call setblocking(False) on the socket wrapper returned by ssl.wrap_socket (after negotiation).  Previously the underlying socket was in non-blocking mode but the SSL wrapper was not.  Given that you say the server is a little slow to respond I assume that you should be getting some exceptions thrown by recv indicating blocking but instead you seem to be getting some junk data returned instead.  If removing line 1024 of http/client.py in master fixes the problem that would confirm the issue.  The version of OpenSSL in use may be relevant too.

**Comment by karurosu** [comment]
I have tried with master again.
The response still has garbage at the beginning.

I am not using SSL so the change in line 1024 had no effect.

Version info: Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32

Let me know if I can help you test something else.

**Comment by swl10** [comment]
OK - I have identified the issue.  When I updated the http sub-package for Python 3 support just after the last PyPi release I changed use of StringIO to BytesIO for the response stream.  There's a really important difference that I hadn't appreciated.  The truncate method of StringIO moves the stream pointer back to 0 but the truncate method of BytesIO does not.  This was affecting you because you were getting a 401 response, pyslet resends the request and truncates the current response to replace it with the new response.  For BytesIO, a truncate without a corresponding seek means the next write will write zeros into the buffer up to the stream position.  You can see that the number of zeros is exactly the same as the content-length of the original 401 response body.

I wasn't able to reproduce the problem because I suppressed the 401 in my own tests by calling add_success_path on the credentials object before adding it to the client.  As soon as I commented out this line I was able to reproduce the error myself.  Thanks for spotting this tricky issue.
